name: Java CI

on:
  push:
    branches: [ "change" ]
  pull_request:
    branches: [ "change" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ./repo
          key: ${{ runner.os }}-mav-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-mav-
          
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
          
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
