name: Java CI

on:
  push:
    branches: [ "change" ]
  pull_request:
    branches: [ "change" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      
      - name: Build with Maven
        run: mvn -B clean install package --file src/pom.xml
      - run: mkdir staging && cp src/target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
          
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
