name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Configure Git user
        run: |
          git config --global user.name "$GITHUB_ACTOR" 
          git config --global --get user.name
        id: actor_email
         actor_username=${{ github.actor }}
         actor_email=$(curl -s -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" \ "https://api.gtihub.com/users/$actor_username/emails" | jq -r '.[0].email')

                 echo "::set-output name=actor_email::$actor_email"
                 echo "github actor mail:${{step.actor_email.outputs.actor_email }}"
      
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2 
             
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
          
