name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: increment version
        id: increment_version
        run: |

         CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
         echo "current version: $CURRENT_VERSION"

         NEXT_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF+1;} 1' | sed 's/ /./g')
         echo "Next version: $NEXT_VERSION"

         echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          
          
      
      - name: Build with Maven
        run: mvn -B clean install -DnewVersion=${NEXT_VERSION}  package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging 

      - name: Download the artifacts
        uses: actions/download-artifact@v3
        with: 
         name: Package
         path: Staging
